name: Telnyx Cucumber Testing 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./
          browser: chrome
          build: npm install
          start: npm run test
          wait-on: "https://telnyx.com/"
        env:
            GITHUB_TOKEN: ${{ secrets.TELNYXCUCUMBERTESTING }}
          
