name: Telnyx Cucumber Testing 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./
          build: npm install
          browser: electron
          wait-on: "https://telnyx.com/"
        env:
            GITHUB_TOKEN: ${{ secrets.TELNYXCUCUMBERTESTING }}
      - name: Generate reports
        run: npm run clear && npm run html-report
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './report/output.html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      

