name: Telnyx Cucumber Testing 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./
          build: npm install
          browser: electron
          wait-on: "https://telnyx.com/"
        continue-on-error: true
        env:
            GITHUB_TOKEN: ${{ secrets.TELNYXCUCUMBERTESTING }}
      - name: Generate reports
        run: npm run html-report
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TELNYXCUCUMBERTESTING }}
          publish_dir: ./report
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      

